// Constraint Error Codes
// Коды ошибок для слоя ограничений областей.

export const CONSTRAINT_ERRORS = {
  INVALID_CONSTRAINT: "INVALID_CONSTRAINT",
  INVALID_LIMITS: "INVALID_LIMITS",
  AREA_BELOW_MIN_SIZE: "AREA_BELOW_MIN_SIZE",
  AREA_ABOVE_MAX_SIZE: "AREA_ABOVE_MAX_SIZE",
  MOVE_LOCKED: "MOVE_LOCKED",
  RESIZE_LOCKED: "RESIZE_LOCKED"
};
