// Rejection Error Codes
// Коды причин, по которым движок отклоняет действие.

export const REJECTION_ERRORS = {
  UNKNOWN_REJECTION: "UNKNOWN_REJECTION",
  AREA_COLLISION: "AREA_COLLISION",
  AREA_OUT_OF_BOUNDS: "AREA_OUT_OF_BOUNDS",
  INVALID_AREA: "INVALID_AREA",
  INVALID_OPERATION: "INVALID_OPERATION",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",
  MOVE_LOCKED: "MOVE_LOCKED",
  RESIZE_LOCKED: "RESIZE_LOCKED",
  NO_FREE_SPACE: "NO_FREE_SPACE"
};
