export const SCENE_OPERATION_ERRORS = {
  INVALID_SCENE_OPERATION: "INVALID_SCENE_OPERATION",
  UNKNOWN_SCENE_OPERATION: "UNKNOWN_SCENE_OPERATION",
  LAYER_OPERATION_BLOCKED: "LAYER_OPERATION_BLOCKED",
  SIDEBAR_REFLOW_FAILED: "SIDEBAR_REFLOW_FAILED",
  NO_SPACE_AFTER_FIXED_SIDEBAR: "NO_SPACE_AFTER_FIXED_SIDEBAR",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION"
};

export function isSceneOperationError(value) {
  return Object.values(SCENE_OPERATION_ERRORS).includes(value);
}
