// Layout error codes
// Единый источник кодов ошибок для координат и layout-валидации.

export const LAYOUT_ERRORS = {
  INVALID_NUMBERS: "INVALID_NUMBERS",
  INVALID_INTEGER: "INVALID_INTEGER",
  INVALID_SIZE: "INVALID_SIZE",
  OUT_OF_GRID: "OUT_OF_GRID",
  DUPLICATE_ID: "DUPLICATE_ID",
  MISSING_ID: "MISSING_ID",
  AREA_COLLISION: "AREA_COLLISION",
  INVALID_METRICS: "INVALID_METRICS",
  PROCESS_FAILED: "PROCESS_FAILED"
};
