export const NAVIGATION_ISSUE_CODES = {
  INVALID_CONTEXT: "INVALID_CONTEXT",
  INVALID_METRICS: "INVALID_METRICS",
  ACTIVE_PAGE_NOT_FOUND: "ACTIVE_PAGE_NOT_FOUND",
  ACTIVE_WORKSPACE_NOT_FOUND: "ACTIVE_WORKSPACE_NOT_FOUND",
  NAVIGATION_ITEM_WITHOUT_TARGET: "NAVIGATION_ITEM_WITHOUT_TARGET",
  ROUTE_WITHOUT_WORKSPACE: "ROUTE_WITHOUT_WORKSPACE",
  RESERVED_AREA_OUT_OF_WORKSPACE: "RESERVED_AREA_OUT_OF_WORKSPACE",
  HOST_USABLE_WORKSPACE_MISMATCH: "HOST_USABLE_WORKSPACE_MISMATCH"
};
